service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: index.handler
    events:
      - httpApi:
          path: hello
          method: get
